//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInfoAngularPart2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDB
    {
        public string EmployeeStatus { get; set; }
        public string EmployeeID { get; set; }
        public string SSSNumber { get; set; }
        public string TINNumber { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Honorifics { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyContact { get; set; }
    }
}
